"""Offline fundamental fixtures for deterministic Batch 1 tests and demos."""

from __future__ import annotations

from tradingagents.factor_intelligence.schemas import SecurityFundamentalSnapshot

# Representative point-in-time snapshots (not live quotes).
_FIXTURES: dict[str, dict] = {
    "AAPL": {
        "name": "Apple",
        "sector": "Technology",
        "market_cap": 3.2e12,
        "price": 200.0,
        "book_value_per_share": 4.5,
        "trailing_eps": 6.5,
        "free_cash_flow": 1.0e11,
        "revenue_growth": 0.06,
        "earnings_growth": 0.08,
        "return_on_equity": 1.4,
        "return_on_assets": 0.28,
        "gross_margins": 0.46,
        "debt_to_equity": 1.5,
        "beta": 1.15,
        "trailing_volatility": 0.22,
        "average_dollar_volume": 1.2e10,
        "dividend_yield": 0.005,
        "momentum_12_1": 0.18,
        "momentum_6m": 0.10,
    },
    "MSFT": {
        "name": "Microsoft",
        "sector": "Technology",
        "market_cap": 3.0e12,
        "price": 420.0,
        "book_value_per_share": 35.0,
        "trailing_eps": 12.0,
        "free_cash_flow": 6.5e10,
        "revenue_growth": 0.14,
        "earnings_growth": 0.16,
        "return_on_equity": 0.35,
        "return_on_assets": 0.18,
        "gross_margins": 0.69,
        "debt_to_equity": 0.4,
        "beta": 0.95,
        "trailing_volatility": 0.20,
        "average_dollar_volume": 9.0e9,
        "dividend_yield": 0.008,
        "momentum_12_1": 0.22,
        "momentum_6m": 0.12,
    },
    "AMD": {
        "name": "AMD",
        "sector": "Technology",
        "market_cap": 2.5e11,
        "price": 160.0,
        "book_value_per_share": 35.0,
        "trailing_eps": 2.5,
        "free_cash_flow": 2.0e9,
        "revenue_growth": 0.20,
        "earnings_growth": 0.25,
        "return_on_equity": 0.12,
        "return_on_assets": 0.07,
        "gross_margins": 0.50,
        "debt_to_equity": 0.2,
        "beta": 1.75,
        "trailing_volatility": 0.45,
        "average_dollar_volume": 4.0e9,
        "dividend_yield": 0.0,
        "momentum_12_1": 0.55,
        "momentum_6m": 0.30,
    },
    "NVDA": {
        "name": "NVIDIA",
        "sector": "Technology",
        "market_cap": 3.1e12,
        "price": 120.0,
        "book_value_per_share": 8.0,
        "trailing_eps": 3.0,
        "free_cash_flow": 4.0e10,
        "revenue_growth": 0.80,
        "earnings_growth": 1.20,
        "return_on_equity": 0.90,
        "return_on_assets": 0.50,
        "gross_margins": 0.75,
        "debt_to_equity": 0.25,
        "beta": 1.65,
        "trailing_volatility": 0.48,
        "average_dollar_volume": 2.0e10,
        "dividend_yield": 0.0003,
        "momentum_12_1": 0.70,
        "momentum_6m": 0.35,
    },
    "JPM": {
        "name": "JPMorgan",
        "sector": "Financial Services",
        "market_cap": 5.5e11,
        "price": 200.0,
        "book_value_per_share": 110.0,
        "trailing_eps": 16.0,
        "free_cash_flow": None,
        "revenue_growth": 0.08,
        "earnings_growth": 0.10,
        "return_on_equity": 0.15,
        "return_on_assets": 0.012,
        "gross_margins": None,
        "debt_to_equity": None,
        "beta": 1.10,
        "trailing_volatility": 0.25,
        "average_dollar_volume": 3.0e9,
        "dividend_yield": 0.023,
        "momentum_12_1": 0.15,
        "momentum_6m": 0.08,
    },
    "XOM": {
        "name": "Exxon",
        "sector": "Energy",
        "market_cap": 4.5e11,
        "price": 110.0,
        "book_value_per_share": 55.0,
        "trailing_eps": 9.0,
        "free_cash_flow": 3.5e10,
        "revenue_growth": -0.05,
        "earnings_growth": -0.10,
        "return_on_equity": 0.16,
        "return_on_assets": 0.08,
        "gross_margins": 0.30,
        "debt_to_equity": 0.2,
        "beta": 0.90,
        "trailing_volatility": 0.28,
        "average_dollar_volume": 2.5e9,
        "dividend_yield": 0.035,
        "momentum_12_1": -0.05,
        "momentum_6m": -0.02,
    },
    "NEE": {
        "name": "NextEra",
        "sector": "Utilities",
        "market_cap": 1.5e11,
        "price": 75.0,
        "book_value_per_share": 30.0,
        "trailing_eps": 3.2,
        "free_cash_flow": -2.0e9,
        "revenue_growth": 0.05,
        "earnings_growth": 0.07,
        "return_on_equity": 0.10,
        "return_on_assets": 0.03,
        "gross_margins": 0.55,
        "debt_to_equity": 1.8,
        "beta": 0.55,
        "trailing_volatility": 0.18,
        "average_dollar_volume": 8.0e8,
        "dividend_yield": 0.028,
        "momentum_12_1": 0.04,
        "momentum_6m": 0.02,
    },
    "SPY": {
        "name": "SPDR S&P 500",
        "sector": None,
        "asset_type": "etf",
        "market_cap": 5.0e11,
        "price": 500.0,
        "book_value_per_share": None,
        "trailing_eps": None,
        "revenue_growth": 0.08,
        "earnings_growth": 0.08,
        "return_on_equity": None,
        "return_on_assets": None,
        "gross_margins": None,
        "beta": 1.0,
        "trailing_volatility": 0.16,
        "average_dollar_volume": 3.0e10,
        "dividend_yield": 0.013,
        "momentum_12_1": 0.12,
        "momentum_6m": 0.07,
    },
    "GLD": {
        "name": "SPDR Gold",
        "sector": "Basic Materials",
        "asset_type": "etf",
        "market_cap": 6.0e10,
        "price": 220.0,
        "beta": 0.15,
        "trailing_volatility": 0.14,
        "average_dollar_volume": 1.5e9,
        "dividend_yield": 0.0,
        "momentum_12_1": 0.20,
        "momentum_6m": 0.10,
        "revenue_growth": None,
        "earnings_growth": None,
    },
}


def fixture_snapshot(symbol: str, *, as_of: str) -> SecurityFundamentalSnapshot | None:
    raw = _FIXTURES.get(symbol.strip().upper())
    if raw is None:
        return None
    return SecurityFundamentalSnapshot(
        symbol=symbol,
        as_of=as_of,
        source="fixture",
        source_quality=0.85,
        **raw,
    )


def fixture_universe(symbols: list[str], *, as_of: str) -> list[SecurityFundamentalSnapshot]:
    out: list[SecurityFundamentalSnapshot] = []
    for symbol in symbols:
        snap = fixture_snapshot(symbol, as_of=as_of)
        if snap is not None:
            out.append(snap)
    return out


def synthetic_snapshot_from_position(
    symbol: str,
    *,
    as_of: str,
    market_value: float | None = None,
) -> SecurityFundamentalSnapshot:
    """Fallback when no fixture/vendor data exists — low confidence."""
    mv = abs(market_value or 1e9)
    return SecurityFundamentalSnapshot(
        symbol=symbol,
        as_of=as_of,
        sector="Unknown",
        market_cap=max(mv * 50.0, 1e9),
        price=100.0,
        beta=1.0,
        trailing_volatility=0.30,
        average_dollar_volume=max(mv * 0.05, 1e7),
        source="synthetic",
        source_quality=0.35,
    )
